#!/bin/bash
# PURPOSE: Submit FITS file from pipeline to archive
#
# EXAMPLE: 

#Absolute path to this script
SCRIPT=$(readlink -f $0)
#Absolute path this script is in
SCRIPTPATH=$(dirname $SCRIPT)


usage="USAGE: $cmd [options] fitsFile ...
"

MINARGS=1
if [ $# -lt $MINARGS ]; then
    echo >&2 "ERROR: Wrong number of arguments.  Got $#, expected $MINARGS"
    echo >&2 "$usage"
    exit 2
fi

##############################################################################

opts="-o _PROPID=2014B-0461"
for filename; do
    lp -d astro -o __source=pipeline $opts ${filename}    
done
