#!/bin/bash
# PURPOSE: Initiate submit of fits file to archive.
#   Sets options for use by tada at valley to add to fits header.
#   Logs to syslog (/var/log/messages)
#
# EXAMPLES:
#   raw_post myfile.fits.fz
#   raw_post myfile.fits.fz
#   raw_post -p fake_instr ct582021.fits.fz 
#
# CONSIDERATIONS:
#   It might be better to source the personality file once for each
#   file processed. But that would eliminate time savings from calling
#   postproc with a list of files.  Besides, if you want the same
#   personality used with multiple files, you can always invoke this
#   script on one file at a time.
#
# PERSONALTIES:
#   A "personality" file is a way of providing instrument or dome
#   specific options without cluttering up the core of tada.  All is
#   done by using the "options" ("-o") of the CUPS "lp" command.  Two
#   kinds of things can be passed to tada through lp options: 1. FITS
#   field value overrides, 2. ordered list of header calculation
#   functions (HCF, mapping functions).  The HCFs are all defined in:
#   tada/hdr_calc_funcs.py If you need new HCFs, you'll have to define
#   them there and reinstall tada.
#
# AUTHORS: S. Pothier

function finish {
    logger -p info "postproc: Normal exit of: $(basename $0) $*"
}
trap finish EXIT

function abort {
    echo "ABORT of postproc"
    logger -p err "postproc: Aborted($?) run of: $(basename $0) $*"
}
trap abort ERR SIGINT SIGTERM

#!cmd=`basename $0`
#!dir=`dirname $0`

return_code=0
#Absolute path to this script
SCRIPT=$(readlink -f $0)
#Absolute path this script is in
SCRIPTPATH=$(dirname $SCRIPT)
PERSPATH=$(readlink -f "$SCRIPTPATH/../personalities")

PATH=$SCRIPTPATH:$PATH

OPTIONS=""
LPOPTIONS=""
TADAOPTS=""
VERBOSE=0
TIMEOUT=30
#!SUBMITTED=/var/log/tada/postproc.rcvd
filename=$1

# Error codes
NEED_HELP=1
BAD_ARGUMENT=2
MISSING_ARGUMENT=3
BAD_OPTION=4
BAD_PERSONALITY=5

usage="USAGE: $cmd [options] file [file ...]
OPTIONS:
  -o <specific option>:: Add option to submit.  Can use multiple times.
     (default=NONE)

  -p <personality>:: Add set of options to submit.  Can use multiple times.
     (default=NONE)

  -t <seconds>:: Seconds to wait for match to show up in manifest 
     (default=$TIMEOUT)

  -v :: Verbose output
     (default=not verbose)
"
#!  -s <filename>:: Write info about what was submitted to this file.
#!     (default=$SUBMITTED)



while getopts "ho:p:s:t:v" opt; do
    #!echo "opt=<$opt>"
    case $opt in
	h)
            echo "$usage"
            exit $NEED_HELP
            ;;
	c)
            CLEAR=1
            ;;
        v)
            VERBOSE=1
            ;;
        o)
	    LPOPTIONS="$LPOPTIONS -o ${OPTARG}"
            ;;
        p)
	    # appends to $TADAOPTS
	    pfile=${PERSPATH}/${OPTARG}.personality
	    if [ -f $pfile ]; then
		source $pfile
	    else
		echo "ERROR: File given as -p option ($pfile) was not found or not a regular file. Aborting!"  1>&2
		exit $BAD_PERSONALITY
	    fi
            ;;
        #!s)
        #!    SUBMITTED=$OPTARG
        #!    ;;
        t)
            TIMEOUT=$OPTARG
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit $BAD_OPTION
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit $BAD_ARGUMENT
            ;;

    esac
done
#echo "OPTIND=$OPTIND"
for (( x=1; x<$OPTIND; x++ )); do shift; done


RAC=1 # Required Argument Count
if [ $# -lt $RAC ]; then
    echo "Not enough non-option arguments. Expect at least $RAC."
    echo >&2 "$usage"
    exit $MISSING_ARGUMENT
fi


##############################################################################

strs=""
for filename; do
    base=`basename $filename`
    lpcmd="lp -d astro ${LPOPTIONS} -o __filename=$filename ${TADAOPTS} ${filename}"
    req=`$lpcmd`
    lpstat=$?
    return_code=$lpstat
    id=`echo $req | awk '{ print substr($4,7) }'`
    ufile=$USER/$id/$base
    strs="$strs $ufile"
    stamp=`date '+%Y.%m.%d_%H.%M'`;
    #! echo "$stamp $filename $return_code USER=$USER id=$id" >> $SUBMITTED

    if [ $VERBOSE -gt 0 ]; then
	echo "# Executed: $lpcmd"
	echo "# Submit ($req) status: $lpstat"
	echo "# Submitted: $ufile"
    else
	echo "$req"
    fi
done

#! echo "# Wrote status to $SUBMITTED"

exit $return_code
